name: Update Dockerfiles

on:
  schedule:
    - cron:  '40 16 * * *'
jobs:
  deploy:
    name: Update Dockerfiles
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout the repository
        uses: actions/checkout@v7

      - name: 📤 Update Dockerfiles
        uses: ludeeus/dockerfile-updater@eaf8ea79220d076eb46c127fa9895e3de3e0a512
        with:
          token: ${{ secrets.GITHUB_TOKEN }}